app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /easy_admin
oneup_uploader:
    resource: .
    type: uploader
2fa_login:
    path: /2fa
    defaults:
        _controller: "scheb_two_factor.form_controller:form"
2fa_login_check:
    path: /2fa_check
endroid_qr_code:
    resource: "@EndroidQrCodeBundle/Resources/config/routes.yaml"
    prefix: /qr-code
