version: "3"

networks:
  samlidp:


services:
  samli:
    image: "samli/nren"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - samlidp
    volumes:
      #- /path/to/idp_logo:/app/web/images/idp_logo
      # - /samlidp.sqlite:/samlidp.sqlite
      - /samlidp-data:/data
      - /samlidp-data/config:/app/app/config/
    restart: unless-stopped
    environment:
      - "SAMLIDP_RUNNING_MODE=frontend"
      - "SAMLIDP_HOSTNAME=localidp"
      - "VAULT_PASS=pass"
      - "DATABASE_DRIVER=pdo_sqlite"
      #- "DATABASE_USER=symfony"
      #- "DATABASE_PASSWORD=secret"
      - "DATABASE_PATH=%kernel.project_dir%/../app/sqlite.db"
      - "MAILER_HOST=smtp"
      - "MAILER_PORT=1025"
      #- "MAILER_PORT=1025"
      #- "MAILER_ENCRYPTION=~"
      - "MAILER_USER="
      - "MAILER_PASSWORD="
      - "MAILER_SENDER=tothp@sztaki.hu"
      - "ROLLBAR_ACCESS_TOKEN=fake"
      - "LOGGLY_AUTH_TOKEN=fake"
      - "LOGGLY_TAG=samli-ssp"
      - "REMOTE_LOGSERVER_AND_PORT=host_or_ip:port"
    depends_on:
      - smtp

  smtp:
    image: mailhog/mailhog:latest
    ports:
      - "127.0.0.1:8025:8025"
      - "1025:1025"
    networks:
      - samlidp
#        aliases:
#          - smtp
