<?php

namespace AppBundle\Repository;

/**
 * ApiTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
