<?php

namespace AppBundle\Repository;

/**
 * FederationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FederationRepository extends \Doctrine\ORM\EntityRepository
{
}
