<?php

namespace AppBundle\Repository;

/**
 * IdPAuditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdPAuditRepository extends \Doctrine\ORM\EntityRepository
{
}
