<?php

namespace AppBundle\Repository;

/**
 * IdPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdPRepository extends \Doctrine\ORM\EntityRepository
{
}
