<?php

namespace AppBundle\Repository;

/**
 * OrganizationElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizationElementRepository extends \Doctrine\ORM\EntityRepository
{
}
