<?php

namespace AppBundle\Repository;

/**
 * UserIdpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserIdpRepository extends \Doctrine\ORM\EntityRepository
{
}
