<?php

namespace AppBundle\Repository;

use MadWizard\WebAuthn\Format\ByteBuffer;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param ByteBuffer $userHandle
     * @return mixed
     */
    public function findOneByUserHandle(ByteBuffer $userHandle)
    {
        return $this->findOneByUserHandleBase64Url($userHandle->getBase64Url());
    }
}
