<?php

namespace AppBundle\Repository;

/**
 * WebauthnCredentialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebauthnCredentialRepository extends \Doctrine\ORM\EntityRepository
{
}
